version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: smart_obd_postgres
    restart: "no"
    environment:
      POSTGRES_DB: smart_obd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - smart_obd_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    container_name: smart_obd_backend
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/smart_obd
      NODE_ENV: production
    ports:
      - "3000:3000"


volumes:
  smart_obd_postgres_data:
