import { Injectable } from '@nestjs/common';
import * as PDFDocument from 'pdfkit';

@Injectable()
export class DiagnosticReportService {
  async generateReport(session: any): Promise<Buffer> {
    return new Promise((resolve) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      // Header
      doc.fontSize(20).fillColor('#007BC0').text('Diagnostic Report', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#666').text(`Date: ${new Date(session.createdAt).toLocaleDateString()}`, { align: 'center' });
      doc.moveDown(1.5);

      // Vehicle info
      if (session.vehicle) {
        doc.fontSize(14).fillColor('#333').text('Vehicle Information');
        doc.moveDown(0.3);
        doc.fontSize(10).fillColor('#555');
        doc.text(`Brand: ${session.vehicle.brand}`);
        doc.text(`Model: ${session.vehicle.model}`);
        doc.text(`Year: ${session.vehicle.year}`);
        if (session.vehicle.vin) doc.text(`VIN: ${session.vehicle.vin}`);
        if (session.vehicle.mileage) doc.text(`Mileage: ${session.vehicle.mileage.toLocaleString()} km`);
        doc.moveDown(1);
      }

      // Summary
      if (session.result) {
        doc.fontSize(14).fillColor('#333').text('Analysis Summary');
        doc.moveDown(0.3);
        doc.fontSize(10).fillColor('#555').text(session.result.summary);
        doc.moveDown(1);
      }

      // DTC Codes
      doc.fontSize(14).fillColor('#333').text(`DTC Codes (${session.dtcs?.length || 0})`);
      doc.moveDown(0.5);

      if (session.dtcs && session.dtcs.length > 0) {
        // Table header
        const tableTop = doc.y;
        doc.fontSize(9).fillColor('#007BC0');
        doc.text('Code', 50, tableTop, { width: 60 });
        doc.text('Description', 120, tableTop, { width: 280 });
        doc.text('Severity', 410, tableTop, { width: 80 });
        doc.moveDown(0.3);

        doc.strokeColor('#ddd').lineWidth(0.5)
          .moveTo(50, doc.y)
          .lineTo(545, doc.y)
          .stroke();
        doc.moveDown(0.3);

        // Table rows
        for (const dtc of session.dtcs) {
          const y = doc.y;
          if (y > 720) {
            doc.addPage();
          }

          const severityLabel = this.getSeverityLabel(dtc.severity);
          const color = this.getSeverityColor(dtc.severity);

          doc.fontSize(9).fillColor('#333');
          doc.text(dtc.code, 50, doc.y, { width: 60 });
          doc.text(dtc.description, 120, doc.y - doc.currentLineHeight(), { width: 280 });
          doc.fillColor(color).text(severityLabel, 410, doc.y - doc.currentLineHeight(), { width: 80 });
          doc.moveDown(0.5);
        }
      }

      // Footer
      doc.moveDown(2);
      doc.fontSize(8).fillColor('#999').text(
        'Generated by Smart OBD Diagnostic Platform. This report is for informational purposes only.',
        { align: 'center' },
      );

      doc.end();
    });
  }

  private getSeverityLabel(severity: number): string {
    switch (severity) {
      case 5: return 'CRITICAL';
      case 4: return 'HIGH';
      case 3: return 'MEDIUM';
      case 2: return 'LOW';
      default: return 'INFO';
    }
  }

  private getSeverityColor(severity: number): string {
    switch (severity) {
      case 5: return '#ef4444';
      case 4: return '#f97316';
      case 3: return '#eab308';
      case 2: return '#22c55e';
      default: return '#666666';
    }
  }
}
